### ISSUE TITLE
v0.1 Roadmap

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [Lukas-Heiligenbrunner/AURCache#9]
Roadmap for being able to make this Repo public and Publishing a first  v0.1 Release candidate.

High prio:
- [x] Average build time header field not populated
- [x] Active builds header field a bit useless when there is always one active build
    * replace with enqueued builds

- [ ] Settings page
- [x] Proper header for builds and AUR page
- [x] Right graph instead of active builds display enqueued builds
- [x] Reorganize Dashboard file/class structure
- [x] Initial empty tables -> display some info to add pkgs

Low Prio:

- [ ] Auto Housekeeping features
    * Auto cleanup old versions and keep only n
    * delete old build logs

- [x] Support Posgresql Backend
- [x] Build pkgs in seperate archroot
    (kind of, builds are in seperate docker containers now)
